---
constraints:
  - 'UNIQUE( program_id, role, givenname, surname )'
givenname: VARCHAR(32)
id: INTEGER PRIMARY KEY AUTOINCREMENT
lastupdate: INT
program_id: VARCHAR(16)
role: VARCHAR(16)
surname: VARCHAR(32)
