---
constraints:
  - UNIQUE( program_id )
id: INTEGER PRIMARY KEY AUTOINCREMENT
lastupdate: INTEGER
link: VARCHAR(128)
percent: INTEGER
program_id: VARCHAR(16)
runtime: VARCHAR(8)
synopsis: VARCHAR(512)
title: VARCHAR(128)
