---
command: text
message: text
queueid: varchar(32)
started: int
pid: int
status: int
signal: int
pidfile: varchar(128)
logfile: varchar(128)
childpid: int
lastupdate: int
output: text
id: INTEGER PRIMARY KEY AUTOINCREMENT
seen: int
