---
id: INTEGER PRIMARY KEY AUTOINCREMENT
subject: TEXT
subject_text: TEXT
body: TEXT
coalesce: VARCHAR(256)
mailbox: VARCHAR(32)
link: VARCHAR(512)
icon: VARCHAR(256)
key: VARCHAR(32)
username: VARCHAR(64)
color: VARCHAR(16)
seen: INTEGER
score: INTEGER
lastupdate: INTEGER
