command_queue:
  command: text
  message: text
  queueid: varchar(32)
  started: int
  pid: int
  status: int
  signal: int
  pidfile: varchar(128)
  logfile: varchar(128)
  childpid: int
  lastupdate: int
  output: text
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  seen: int

message_queue:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  date: VARCHAR(32)
  subject: VARCHAR(256)
  data: TEXT
  hostname: VARCHAR(32)
  seen: INTEGER
  lastupdate: INTEGER

message_queue_rejected:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  date: VARCHAR(32)
  subject: VARCHAR(256)
  data: TEXT
  hostname: VARCHAR(32)
  seen: INTEGER
  lastupdate: INTEGER

