---
rules:

  - name: RSS feed entries
    condition: key matches ^RSS AND contains body
    rules:
      - name: slashdot image remover
        condition: key matches slashdot
        plugin: ImageStrip
        config:
          field: body
      - name: cl-fu image remover
        condition: key matches cl-fu
        plugin: ImageStrip
        config:
          field: body
      - name: cpan messages in 'cpan' mailbox
        conditon: key matches cpan
        plugin: Maildir
        config:
          path: /Users/wu/wubot/mail
          mailbox: cpan
        last_rule: 1
      - name: sunspot
        condition: key matches sunspot
        rules:
          - name: no storms
            condition: body matches No space weather storms
            last_rule: 1
          - name: normal conditions
            condition: body matches Normal.*Normal.*Normal
            last_rule: 1

  - name: strip HTML from subject
    condition: contains subject
    plugin: HTMLStrip
    config:
      field: subject
      newfield: subject_text
    rules:
      - name: contains subject and body
        condition: contains body
        rules:
          - name: strip body HTML
            plugin: HTMLStrip
            config:
              field: body
              newfield: body_text
          - name: store message in maildir
            plugin: Maildir
            config:
              path: /Users/wu/wubot/mail

  - name: Ping Time RRD
    condition: key matches ^Ping
    plugin: RRD
    config:
      base_dir: /Users/wu/wubot/rrd
      fields:
        average: GAUGE
      graph_options:
        lower_limit: 0
        upper_limit: 1
        right-axis: 1:0
        width: 375

  - name: OS X Idle
    condition: key matches ^OsxIdle
    rules:
      - name: store in SQLite database
        plugin: SQLite
        config:
          file: /Users/wu/wubot/sqlite/idle.sql
          tablename: idle
          schema:
            id: INTEGER PRIMARY KEY AUTOINCREMENT
            idle_min: int
            active_min: int
            idle_state: int
            lastupdate: int
      - name: add active_min and idle_min to rrd
        plugin: RRD
        config:
          base_dir: /Users/wu/wubot/rrd
          fields:
            idle_min: GAUGE
            active_min: GAUGE
          period:
            - day
            - week
          graph_options:
            lower_limit: 0
            upper_limit: 60
            rigid: ""
            sources:
              - active_min
              - idle_min
            source_colors:
              - FF9933
              - 9933FF
            source_drawtypes:
              - AREA
              - AREA
            right-axis: 1:0
            width: 375

  - name: Work Hours
    condition: key matches ^WorkHours
    rules:
      - name: store in SQLite
        plugin: SQLite
        config:
          file: /Users/wu/wubot/sqlite/workhours.sql
          tablename: workhours
          schema:
            id: INTEGER PRIMARY KEY AUTOINCREMENT
            idle_hours: int
            active_hours: int
            total_hours: int
      - name: store in RRD
        plugin: RRD
        config:
          base_dir: /Users/wu/wubot/rrd
          fields:
            idle_hours: GAUGE
            active_hours: GAUGE
            total_hours: GAUGE
          period:
            - day
            - week
            - month
          heartbeat: 1800
          graph_options:
            sources:
              - idle_hours
              - active_hours
              - total_hours
            source_colors:
              - 9933FF
              - FF9933
              - 3399FF
            source_drawtypes:
              - LINE
              - AREA
              - LINE
            right-axis: 1:0
            width: 375

  - name: Uptime - add load to rrd
    condition: key matches ^Uptime
    plugin: RRD
    config:
      base_dir: /Users/wu/wubot/rrd
      fields:
        load01: GAUGE
        load05: GAUGE
        load15: GAUGE
      graph_options:
        upper_limit: 1
        lower_limit: 0
        sources:
          - load01
          - load05
          - load15
        source_colors:
          - 9933FF
          - FF9933
          - 33FF99
        source_drawtypes:
          - AREA
          - LINE
          - LINE
        right-axis: 1:0
        width: 375

  - name: notifications
    condition: contains subject
    rules:
      - name: remove key field for messages that came from AppWubot
        condition: key matches ^AppWubot
        plugin: DeleteField
        config:
          field: key
      - name: growl
        plugin: Growl
        config:
          image_dir: /Users/wu/.icons
      - name: console
        plugin: Console
        config: {}

  - name: forwarding to old wubot
    condition: hostname equals navi AND no_post is false
    rules:
      - name: suppress future growl notifications
        plugin: AddField
        config:
          field: quiet_growl
          value: 1
      - name: suppress future voice notifications
        plugin: AddField
        config:
          field: quiet_voice
          value: 1
      - name: post message
        plugin: MessagePoster
        config:
          url: http://wubot/cgi-bin/wubot-message.cgi


