---
files:
  tv: /Users/wu/wubot/sqlite/xml_tv.sql


#############################################################################
# TV

tv_station:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  station_id: INTEGER
  callsign: VARCHAR(16)
  name: VARCHAR(64)
  affiliate: VARCHAR(64)
  fccnumber: INTEGER
  hide: INTEGER
  lastupdate: INTEGER
  constraints:
    - UNIQUE( station_id, callsign )

tv_lineup:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  lineup_id: INTEGER
  channel: INTEGER
  station_id: INTEGER
  lastupdate: INTEGER
  constraints: 
    - UNIQUE( lineup_id, station_id )

tv_schedule:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  program_id: VARCHAR(16)
  station_id: INTEGER
  start: INTEGER
  duration: VARCHAR(8)
  new: INTEGER
  cc: INTEGER
  stereo: INTEGER
  tv_rating: VARCHAR(16)
  dolby: INTEGER
  hd: INTEGER
  constraints:
    - UNIQUE( program_id, station_id, start )

tv_program:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  program_id: VARCHAR(16)
  title: VARCHAR(128)
  subtitle: VARCHAR(128)
  description: TEXT
  show_type: VARCHAR(64)
  series_id: VARCHAR(64)
  episode_id: VARCHAR(64)
  date: VARCHAR(32)
  mpaa_rating: VARCHAR(16)
  stars: VARCHAR(8)
  runtime: VARCHAR(16)
  year: VARCHAR(16)
  color: VARCHAR(8)
  lastupdate: INT
  constraints:
    - UNIQUE( program_id, title, subtitle, series_id, episode_id )

tv_crew:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  program_id: VARCHAR(16)
  role: VARCHAR(16)
  givenname: VARCHAR(32)
  surname: VARCHAR(32)
  lastupdate: INT
  constraints: 
    - UNIQUE( program_id, role, givenname, surname )

tv_genre:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  program_id: VARCHAR(16)
  genre: VARCHAR(32)
  relevance: INT
  lastupdate: INT
  constraints:
    - UNIQUE( program_id, genre )

tv_score:
  id: INTEGER PRIMARY KEY AUTOINCREMENT
  program_id: VARCHAR(16)
  score: INTEGER
  lastupdate: INTEGER
  constraints:
    - UNIQUE( program_id )

