=head1 NAME

App::Wubot::Guide - guide for using wubot

=head1 GUIDES

The guides are under construction.  Lots more to come!

=over 2

=item L<App::Wubot::Guide::Overview>

Wtf is wubot?

=item L<App::Wubot::Guide::GettingStarted>

Guide to getting started monitoring an RSS feed and reacting to items
in that feed.

=item L<App::Wubot::Guide::FeedFu>

Examples of some of the range of things that can be done with feeds,
including filtering, combining, splitting, stripping images or html,
fetching bodies for summaries, or converting from one format to
another.

=back

=head1 MONITORING

=over 2

=item L<App::Wubot::Guide::ArduinoSensors>

Monitoring arduino sensor data.

=back

=head1 REACTIONS

=over 2

=item L<App::Wubot::Conditions>

Using conditions in rules.

=item L<App::Wubot::Guide::Rules>

A description of the possible fields on rules.

=item L<App::Wubot::Guide::Notifications>

A guide to using notifications.

=back

=head1 GENERAL

=over 2

=item L<App::Wubot::Guide::Debugging>

A guide for debugging monitors and reactions.

=item L<App::Wubot::Guide::MultipleBots>

A guide for running multiple communicating bots

=back






