=head1 NAME

Wubot::Guide - guide for using wubot

=head1 GUIDES

The guides are under construction.  Lots more to come!

=over 2

=item L<Wubot::Guide::Overview>

Wtf is wubot?

=item L<Wubot::Guide::GettingStarted>

Guide to getting started monitoring an RSS feed and reacting to items
in that feed.

=back

=head1 MONITORS

=over 2

=item L<Wubot::Guide::MonitorPlugins>

An overview of the monitor plugins

=item L<Wubot::Guide::ArduinoSensors>

Monitoring arduino sensor data.

=back

=head1 REACTORS

=over 2

=item L<Wubot::Guide::Conditions>

A guide for using conditions in rules.

=item L<Wubot::Guide::Rules>

A description of the possible fields on rules.

=item L<Wubot::Guide::ReactorPlugins>

An overview of the available reactor plugins.

=item L<Wubot::Guide::Notifications>

A guide to using notifications.

=back

=head1 GENERAL

=over 2

=item L<Wubot::Guide::Debugging>

A guide for debugging monitors and reactions.

=item L<Wubot::Guide::MultipleBots>

A guide for running multiple communicating bots

=back






