=head1 NAME

App::Wubot::Guide::WebUI - guide for using the wubot web interface

=head1 DESCRIPTION

The web interface was recently changed from using L<Mojolicious::Lite>
to L<Mojolicious>.  So the instructions for starting up the webui have
changed.

The recommended method for using the web ui is to clone the wubot git
repository and run the web ui from there.

  git clone git://github.com/wu/wubot.git
  cd wubot
  cp config/webui.yaml ~/wubot/config/
  bin/wubot-webui daemon

If you do not have git installed, you can also download and expand the
tarball from github rather than using the 'git clone' command above.

=head1 SEE ALSO

  L<App::Wubot::Web::Rss> - stable

  L<App::Wubot::Web::Notify> - under heavy construction

  L<App::Wubot::Web::Tasks> - alpha

  L<App::Wubot::Web::Tv> - beta

  L<App::Wubot::Web::Graphs> - stable
